---
title: "list_of_column"
output: html_document
---

| id               | ok |
|------------------|----|
| submitdate       | ok |
| lastpage         |    |
| startlanguage    |    |
| seed             |    |
| startdate        |    |
| datestamp        |    |
| dmgender         | ok |
| dmbirth          | ok |
| dmswiss          | ok |
| dmnatio          | ok |
| dmres            | ok |
| dmwork           | ok |
| sssknow          | ok |
| sssmember        | ok |
| sssmember.other. | -  |
| ssstime          | ok |
| trlvl            | ok |
| trlvl.other.     | ok |
| tryear           | ok |
| trcontswiss      | ok |
| trreg            | ok |
| trarea.1.        | ok |
| trarea.2.        | ok |
| trarea.3.        | ok |
| trarea.4.        | ok |
| trarea.5.        | ok |
| trarea.6.        | ok |
| trarea.7.        | ok |
| trarea.8.        | ok |
| trarea.9.        | ok |
| trarea.10.       | ok |
| trarea.11.       | ok |
| trarea.12.       | ok |
| trarea.13.       | ok |
| trarea.14.       | ok |
| trarea.15.       | ok |
| trarea.16.       | ok |
| trarea.17.       | ok |
| trarea.18.       | ok |
| trarea.19.       | ok |
| trarea.other.    | ok |
| trcont.1.        | ok |
| trcont.2.        | ok |
| trcont.3.        | ok |
| trcont.4.        | ok |
| trcont.5.        | ok |
| trcont.6.        | ok |
| trcont.7.        | ok |
| trcont.other.    | ok |
| trcont2          | ok |
| trcont2.other.   | ok |
| plemployed       |    |
| plstatus         |    |
| plstatus.other.  |    |
| plrole           |    |
| plsector         |    |
| plyexp           |    |
| plrate           |    |
| plsenior         |    |
| plsenior.other.  |    |
| plskill.1.       |    |
| plskill.2.       |    |
| plskill.3.       |    |
| plskill.4.       |    |
| plskill.5.       |    |
| plskill.6.       |    |
| plskill.other.   |    |
| ustime.1..1.     |    |
| ustime.1..2.     |    |
| ustime.2..1.     |    |
| ustime.2..2.     |    |
| ustime.3..1.     |    |
| ustime.3..2.     |    |
| ustime.4..1.     |    |
| ustime.4..2.     |    |
| ustime.5..1.     |    |
| ustime.5..2.     |    |
| ustime.6..1.     |    |
| ustime.6..2.     |    |
| issalary         |    |
| issatisf         |    |
| issatisf2.1.     |    |
| issatisf2.2.     |    |
| issatisf2.3.     |    |
| issatisf2.4.     |    |
| issatisf2.5.     |    |
| issatisf2.6.     |    |
| issatisf2.7.     |    |
| issatisf2.8.     |    |
| issatisf2.9.     |    |
| issatisf2.10.    |    |
| issatisf2.11.    |    |
| issatisf2.12.    |    |
| interviewtime    |    |
| groupTime652     |    |
| dmgenderTime     |    |
| dmbirthTime      |    |
| dmswissTime      |    |
| dmnatioTime      |    |
| dmresTime        |    |
| dmworkTime       |    |
| groupTime653     |    |
| sssknowTime      |    |
| sssmemberTime    |    |
| ssstimeTime      |    |
| groupTime654     |    |
| trlvlTime        |    |
| tryearTime       |    |
| trcontswissTime  |    |
| trregTime        |    |
| trareaTime       |    |
| trcontTime       |    |
| trcont2Time      |    |
| groupTime657     |    |
| plemployedTime   |    |
| plstatusTime     |    |
| plroleTime       |    |
| plsectorTime     |    |
| plyexpTime       |    |
| plrateTime       |    |
| plseniorTime     |    |
| plskillTime      |    |
| groupTime663     |    |
| ustimeTime       |    |
| groupTime658     |    |
| issalaryTime     |    |
| issatisfTime     |    |
| issatisf2Time    |    |
